Update CHANGES.rst
schymans/environmental-science-for-sagemath pull request #77
Opened 2019-11-19 12:54 UTC by schymans

Updated changes since previous release.

2019-11-19 14:19 UTC, jirikuncar commented
Hi @schymans, I guess we need to pin the sympy version.

2019-11-19 14:20 UTC, jirikuncar requested changes
Can you pin the sympy version?

2019-11-20 08:29 UTC, schymans reviewed
All good, except that we should update the release date, and possibly the version number.

2019-11-20 09:39 UTC, jirikuncar commented on CHANGES.rst
> +*released 2019-11-19*
```suggestion
*released 2019-11-20*
```

2019-11-20 09:45 UTC, jirikuncar commented on CHANGES.rst
> +``v0.4.0``
and let's directly update to `v0.4.1` as `v0.4.0` was already released on Zenodo
```suggestion
``v0.4.1``
```

2019-11-20 18:32 UTC, jirikuncar approved these changes
LGTM

2019-11-20 18:33 UTC, merged